# Generated by Django 3.0.3 on 2020-06-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0002_auto_20200614_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletters',
            name='subscribe',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
