# Generated by Django 3.0.3 on 2020-06-20 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0006_auto_20200619_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonces',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='annonces.Categories'),
        ),
    ]
