# Generated by Django 3.0.3 on 2020-06-26 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0010_products_catalogue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annonces',
            name='num_like',
        ),
        migrations.CreateModel(
            name='Annonceproperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_like', models.IntegerField(max_length=21, null=True)),
                ('annonce', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='annonces.Annonces')),
            ],
        ),
    ]
