# Generated by Django 3.0.3 on 2020-06-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0011_auto_20200626_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonceproperty',
            name='number_like',
            field=models.IntegerField(null=True),
        ),
    ]
