# Generated by Django 3.0.3 on 2020-06-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0012_auto_20200626_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonces',
            name='annonce_photo',
            field=models.ImageField(blank=True, default='image/default.png', null=True, upload_to=''),
        ),
    ]
