# Generated by Django 3.0.3 on 2020-06-26 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0016_profile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonces',
            name='annonce_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
