# Generated by Django 3.0.3 on 2020-07-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0018_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Villes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Contacts',
        ),
    ]
