# Generated by Django 3.0.3 on 2020-07-02 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0019_auto_20200702_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='villes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='villes',
            name='region_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='villes',
            name='update_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
