# Generated by Django 3.0.3 on 2020-07-02 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0020_auto_20200702_0755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='villes',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='villes',
            name='region_id',
        ),
        migrations.RemoveField(
            model_name='villes',
            name='update_at',
        ),
    ]
