# Generated by Django 3.0.3 on 2020-07-02 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0021_auto_20200702_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonces',
            name='ville',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='annonces.Villes'),
        ),
    ]
