# Generated by Django 3.0.3 on 2020-07-02 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0023_auto_20200702_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='client',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='messages',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='messages',
            name='statut',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='content',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
