# Generated by Django 3.0.3 on 2020-07-05 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0025_auto_20200702_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='subject',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
