# Generated by Django 3.0.3 on 2020-07-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0027_auto_20200705_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='sent',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
