# Generated by Django 3.0.3 on 2020-07-08 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0029_remove_catalogue_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='sent',
        ),
    ]
