# Generated by Django 3.0.3 on 2020-07-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0030_remove_messages_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='statut',
            field=models.TextField(default=10, null=True),
        ),
    ]
