# Generated by Django 3.0.3 on 2020-07-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0031_auto_20200708_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletters',
            name='subscribe',
            field=models.TextField(default=10, null=True),
        ),
    ]
