# Generated by Django 3.0.3 on 2020-07-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0032_auto_20200708_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=200, null=True)),
            ],
        ),
    ]
