# Generated by Django 3.0.7 on 2020-07-20 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0035_auto_20200720_0749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='villes',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='villes',
            name='region_id',
        ),
        migrations.RemoveField(
            model_name='villes',
            name='updated_at',
        ),
    ]
