# Generated by Django 3.0.7 on 2020-07-20 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0036_auto_20200720_0755'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('position', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
