# Generated by Django 3.0.7 on 2020-07-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0037_testimonies'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonies',
            name='content',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
