# Generated by Django 3.0.7 on 2020-07-21 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0040_auto_20200721_2045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annonces',
            old_name='category',
            new_name='subcategory',
        ),
        migrations.AddField(
            model_name='product_subcategories',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='annonces.Product_categories'),
        ),
    ]
