# Generated by Django 3.0.7 on 2020-07-21 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0041_auto_20200721_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_images',
            name='size',
        ),
    ]
