# Generated by Django 3.0.7 on 2020-07-24 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0042_remove_product_images_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='product_image',
        ),
    ]
