# Generated by Django 3.0.7 on 2020-07-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0043_remove_products_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_images',
            name='name',
        ),
        migrations.AddField(
            model_name='product_images',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
