# Generated by Django 3.0.7 on 2020-07-26 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0044_auto_20200726_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='product_color',
        ),
        migrations.RemoveField(
            model_name='products',
            name='product_size',
        ),
    ]
