# Generated by Django 3.0.7 on 2020-07-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0045_auto_20200726_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_quantity',
            field=models.IntegerField(null=True),
        ),
    ]
