# Generated by Django 3.1 on 2020-08-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0049_auto_20200806_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
