# Generated by Django 3.1 on 2020-08-09 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0050_products_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
