# Generated by Django 3.1 on 2020-08-12 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0053_auto_20200809_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='annonces.villes'),
        ),
    ]
