# Generated by Django 3.1 on 2020-08-12 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0054_products_product_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='product_city',
            new_name='villes',
        ),
    ]
