# Generated by Django 3.1 on 2020-08-15 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0055_auto_20200812_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annonces',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='annonces',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='annonces.categories'),
        ),
    ]
