# Generated by Django 3.1 on 2020-08-15 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0056_auto_20200815_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='code',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
