# Generated by Django 3.1 on 2020-08-15 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0057_products_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='code',
        ),
    ]
