# Generated by Django 3.1 on 2020-08-21 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0058_remove_products_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='status',
            field=models.CharField(default=0, max_length=10, null=True),
        ),
    ]
