# Generated by Django 3.1 on 2020-08-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0059_products_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
