# Generated by Django 3.1 on 2020-08-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0060_auto_20200823_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('address', models.CharField(max_length=120)),
            ],
        ),
    ]
