# Generated by Django 3.1 on 2020-08-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0062_webinfo_town'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinfo',
            name='country',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
