# Generated by Django 3.1 on 2020-09-02 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0064_webinfo_webname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annonces',
            name='likes',
        ),
    ]
