# Generated by Django 3.1 on 2020-09-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0066_annonces_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonces',
            name='likes',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
