# Generated by Django 3.1 on 2020-09-03 16:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('annonces', '0067_auto_20200902_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annonces',
            name='likes',
        ),
        migrations.AddField(
            model_name='annonces',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='announce_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
