# Generated by Django 3.1 on 2020-09-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0068_auto_20200903_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annonces',
            name='likes',
        ),
        migrations.AddField(
            model_name='annonces',
            name='likes',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
