# Generated by Django 3.1.1 on 2020-09-19 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0069_auto_20200904_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce_images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('Annonce', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='annonces.annonces')),
            ],
        ),
    ]
