# Generated by Django 3.1.1 on 2020-09-19 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0070_annonce_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annonce_images',
            old_name='Annonce',
            new_name='annonce',
        ),
    ]
