# Generated by Django 3.1.1 on 2020-09-20 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0071_auto_20200919_0815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='reply',
        ),
    ]
