# Generated by Django 3.1.1 on 2020-09-21 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0072_remove_comments_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annonces',
            name='likes',
        ),
    ]
