# Generated by Django 3.1.1 on 2020-09-29 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('annonces', '0073_remove_annonces_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.CharField(max_length=100, null=True)),
                ('tuesday', models.CharField(max_length=100, null=True)),
                ('wednesday', models.CharField(max_length=100, null=True)),
                ('thursday', models.CharField(max_length=100, null=True)),
                ('friday', models.CharField(max_length=100, null=True)),
                ('saturday', models.CharField(max_length=100, null=True)),
                ('sunfay', models.CharField(max_length=100, null=True)),
                ('alldays', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Times',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromTime', models.TimeField()),
                ('toTime', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='subcategories',
            name='category_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(max_length=100, null=True)),
                ('service_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('service_location', models.CharField(max_length=200, null=True)),
                ('service_description', models.TextField(max_length=200, null=True)),
                ('service_status', models.CharField(max_length=50, null=True)),
                ('service_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annonces.categories')),
                ('service_subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annonces.subcategories')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(max_length=100, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annonces.services')),
            ],
        ),
        migrations.CreateModel(
            name='Galleries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annonces.services')),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_status', models.CharField(max_length=200, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annonces.services')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Availabilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annonces.days')),
                ('times', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annonces.times')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
