# Generated by Django 3.1.1 on 2020-09-29 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0075_auto_20200929_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='service_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
