# Generated by Django 3.1.1 on 2020-09-29 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0076_services_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
