# Generated by Django 3.1.1 on 2020-09-30 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0082_auto_20200930_0553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='villes',
            name='region',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='annonces.regions'),
        ),
    ]
