# Generated by Django 3.1.1 on 2020-09-30 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0083_auto_20200930_0741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.AddField(
            model_name='profile',
            name='ville',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='annonces.villes'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='annonces.regions'),
        ),
    ]
