# Generated by Django 3.1.1 on 2020-09-30 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0084_auto_20200930_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='booking_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='booking_notes',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='booking_time',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='service_location',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
