from django.conf.urls import url
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
urlpatterns = [
    # front url
    path('list_services', views.list_services, name='list_services'),
    path('categories', views.categories, name='categories'),
    # user url
    path('mybookings', views.mybookings, name='mybookings'),
    # provider url
    path('myservices', views.myservices, name='myservices'),
    path('save_service', views.save_service, name='save_service'),
    path('service_detail/<int:id>', views.service_detail, name='service_detail'),
    path('bookservice/<int:id>', views.bookservice, name='bookservice'),
    path('inactive', views.inactiveservice, name='inactive'),
    path('postservice', views.postservice, name='postservice'),
    path('bookinglist', views.bookinglist, name='bookinglist'),
    path('availability', views.availability, name='availability'),
    path('profilesetting', views.profilesetting, name='profilesetting'),
    path('get_city', views.fetch_city, name='get_city'),
    path('reviews', views.review, name='reviews'),

    path('', views.home, name='home'),
    path('autocomplete/', views.autocomplete, name='autocomplete'),
    path('sort_by/', views.sort_by, name='sort_by'),
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name='annonces/password_reset.html'), name='reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name='annonces/password_reset_sent.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='annonces/password_reset_form.html'), name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='annonces/password_reset_done.html'), name='password_reset_complete'),
    path('search/', views.search, name='search'),
    path('search_by_category/<int:pk>', views.search_by_category, name='search_by_category'),
    path('like_announce/', views.like_announce, name='like_announce'),
    path('get_subcategories/', views.get_subcategories, name='get_subcategories'),
    path('contact_us/', views.contact_us, name='contact_us'),
    path('annonces/', views.annonces, name='annonces'),
    path('detail_announce/<int:pk>', views.detail_announce, name='detail_announce'),
    path('product_detail/<int:pk>', views.product_detail, name='product_detail'),
    path('see_catalogue/<int:pk>', views.see_catalogue, name='see_catalogue'),
    path('send_message_product/', views.send_message_product, name='send_message_product'),
    path('products/', views.products, name='products'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signupPage, name='signup'),
    path('register/', views.registerPage, name='register'),
    path('activate/<uidb64>/<token>/', views.activate_account, name='activate'),
    path('signup_news', views.signup_news, name='signup_news'),
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('show_profile/<int:pk>', views.show_profile, name='show_profile'),
    path('edit_profile/<int:pk>', views.edit_profile, name='edit_profile'),
    path('post_comment/<int:pk>', views.post_comment, name='post_comment'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('create_announce/', views.create_announce, name='create_announce'),
    path('list_announce/', views.list_announces, name='list_announce'),
    path('edit_announce/<int:pk>', views.update_announce, name='edit_announce'),
    path('delete_announce/<int:pk>', views.delete_announce, name='delete_announce'),
    path('list_products/', views.list_products, name='list_products'),
    path('create_product/', views.create_product, name='create_product'),
    path('edit_product/<int:pk>', views.edit_product, name='edit_product'),
    path('delete_product/<int:pk>', views.delete_product, name='delete_product'),
    path('create_catalogue/', views.create_catalogue, name='create_catalogue'),
    path('list_catalogue/', views.list_catalogue, name='list_catalogue'),
    path('edit_catalogue/<int:pk>', views.edit_catalogue, name='edit_catalogue'),
    path('delete_catalogue/<int:pk>', views.delete_catalogue, name='delete_catalogue'),
    path('presta_show_messages/', views.presta_show_messages, name='presta_show_messages'),
    path('presta_view_message/<int:pk>',views.presta_view_message, name='presta_view_message'),
    path('presta_reply_message/<int:pk>', views.presta_reply_message, name='presta_reply_message'),
    path('delete_message/<int:pk>', views.delete_message, name='delete_message'),
    path('view_message/<int:pk>', views.view_message, name='view_message'),
    path('reply_message/<int:pk>', views.reply_message, name='reply_message'),
    path('reply_to_message', views.reply_to_message, name='reply_to_message'),
    path('comments/', views.comments, name='comments'),
    path('reply_comment/<int:pk>', views.reply_comment, name='reply_comment'),
    path('reply_to_comment', views.reply_to_comment, name='reply_to_comment'),
    path('user_page/', views.user_page, name='user_page'),
    path('user_modify/<int:pk>', views.user_modify, name='user_modify'),
    path('user_show_profile/<int:pk>', views.user_show_profile, name='user_show_profile'),
    path('send_message/', views.send_message, name='send_message'),
    path('sent_message/<int:pk>', views.sent_messages, name='sent_message'),
    path('see_message/<int:pk>', views.see_message, name='see_message'),
    path('user_show_message/<int:pk>', views.show_messages, name='user_show_message'),
    #path('like/', include('like.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
